"""
SFT training script using HuggingFace Trainer API.
Trains Qwen2-0.5B-Instruct on gold standard dataset generated by generate_sft_data_ollama.py

Usage:
    # Train on full dataset
    uv run python sft_train.py --sft_dataset sft_dataset.json --num_examples 750 --output_dir output/sft-750

    # Train on subsets for data efficiency analysis
    uv run python sft_train.py --sft_dataset sft_dataset.json --num_examples 100 --output_dir output/sft-100
    uv run python sft_train.py --sft_dataset sft_dataset.json --num_examples 250 --output_dir output/sft-250
    uv run python sft_train.py --sft_dataset sft_dataset.json --num_examples 500 --output_dir output/sft-500
"""

import os
import json
import argparse
import random
import re
import torch
import numpy as np
from tqdm import tqdm
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)
from torch.nn.utils.rnn import pad_sequence


# ── Regex for extracting answers (reuse from evaluator) ──────────────────────
ANSWER_RE = re.compile(r"<answer>\s*(.*?)\s*</answer>", re.DOTALL)
INT_RE = re.compile(r"[+-]?\d+$")


def extract_answer(text: str) -> str:
    m = ANSWER_RE.search(text)
    return m.group(1).strip() if m else ""


def parse_int(s: str):
    s = s.strip().replace(",", "")
    try:
        f = float(s)
        if f == int(f):
            return int(f)
    except ValueError:
        pass
    if INT_RE.fullmatch(s):
        try:
            return int(s)
        except ValueError:
            pass
    return None


def is_correct(pred: str, gt: str) -> bool:
    pred_i = parse_int(extract_answer(pred))
    gt_i = parse_int(gt.strip().replace(",", ""))
    if pred_i is not None and gt_i is not None:
        return pred_i == gt_i
    return extract_answer(pred).strip() == gt.strip()


# ── Dataset preparation ───────────────────────────────────────────────────────

def load_sft_data(path: str, num_examples: int, seed: int = 42) -> list:
    with open(path) as f:
        data = json.load(f)
    random.seed(seed)
    data = [d for d in data if d.get("response")]  # filter empty
    return random.sample(data, min(num_examples, len(data)))


def build_hf_dataset(examples: list, tokenizer, max_length: int = 1024) -> Dataset:
    """
    Format each example as a chat and tokenize.
    The loss is only computed on the assistant response (completion masking).
    """
    input_ids_list = []
    labels_list = []

    for ex in examples:
        prompt = [
            {"role": "system", "content": (
                "You must reply in exactly the following XML format:\n"
                "<reasoning>\n...your reasoning...\n</reasoning>\n"
                "<answer>\nINTEGER\n</answer>"
            )},
            {"role": "user", "content": ex["question"]},
        ]
        prompt_text = tokenizer.apply_chat_template(
            prompt, tokenize=False, add_generation_prompt=True
        )
        full_text = prompt_text + ex["response"] + tokenizer.eos_token

        prompt_ids = tokenizer(prompt_text, add_special_tokens=False)["input_ids"]
        full_ids = tokenizer(full_text, add_special_tokens=False, max_length=max_length, truncation=True)["input_ids"]

        # Mask prompt tokens in labels so loss only on completion
        labels = [-100] * len(prompt_ids) + full_ids[len(prompt_ids):]
        # Truncate to max_length
        input_ids = full_ids[:max_length]
        labels = labels[:max_length]

        input_ids_list.append(input_ids)
        labels_list.append(labels)

    return Dataset.from_dict({"input_ids": input_ids_list, "labels": labels_list})


# ── Custom data collator ──────────────────────────────────────────────────────

class SFTDataCollator:
    def __init__(self, pad_token_id: int):
        self.pad_token_id = pad_token_id

    def __call__(self, features):
        input_ids = [torch.tensor(f["input_ids"]) for f in features]
        labels = [torch.tensor(f["labels"]) for f in features]

        input_ids = pad_sequence(input_ids, batch_first=True, padding_value=self.pad_token_id)
        labels = pad_sequence(labels, batch_first=True, padding_value=-100)
        attention_mask = (input_ids != self.pad_token_id).long()

        return {"input_ids": input_ids, "labels": labels, "attention_mask": attention_mask}


# ── Evaluation ────────────────────────────────────────────────────────────────

def evaluate_model(model, tokenizer, test_data: list, device: str, max_new_tokens: int = 512) -> float:
    """Evaluate accuracy on test examples."""
    model.eval()
    correct = 0

    for ex in tqdm(test_data, desc="Evaluating"):
        prompt = [
            {"role": "system", "content": (
                "You must reply in exactly the following XML format:\n"
                "<reasoning>\n...your reasoning...\n</reasoning>\n"
                "<answer>\nINTEGER\n</answer>"
            )},
            {"role": "user", "content": ex["question"]},
        ]
        prompt_text = tokenizer.apply_chat_template(
            prompt, tokenize=False, add_generation_prompt=True
        )
        inputs = tokenizer(prompt_text, return_tensors="pt").to(device)

        with torch.inference_mode():
            output = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=False,
                temperature=1.0,
                pad_token_id=tokenizer.pad_token_id,
            )

        completion = tokenizer.decode(output[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
        if is_correct(completion, ex["answer"]):
            correct += 1

    model.train()
    return correct / len(test_data) * 100


# ── Load GSM8K test set ───────────────────────────────────────────────────────

def load_gsm8k_test(num_test: int = 200, seed: int = 42) -> list:
    from datasets import load_dataset
    data = load_dataset("openai/gsm8k", "main")["test"]
    examples = []
    for item in data:
        ans = item["answer"].split("####")[-1].strip().replace(",", "") if "####" in item["answer"] else None
        if ans:
            examples.append({"question": item["question"], "answer": ans})
    random.seed(seed)
    return random.sample(examples, min(num_test, len(examples)))


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", type=str, default="Qwen/Qwen2-0.5B-Instruct")
    parser.add_argument("--sft_dataset", type=str, default="sft_dataset.json")
    parser.add_argument("--num_examples", type=int, default=750, help="Number of SFT training examples")
    parser.add_argument("--output_dir", type=str, default="output/sft")
    parser.add_argument("--num_epochs", type=int, default=3)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--learning_rate", type=float, default=2e-5)
    parser.add_argument("--max_length", type=int, default=1024)
    parser.add_argument("--num_test", type=int, default=200, help="Number of test examples to evaluate on")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)
    torch.manual_seed(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(args.output_dir, exist_ok=True)

    # Load model and tokenizer
    print(f"Loading {args.model_name}...")
    tokenizer = AutoTokenizer.from_pretrained(args.model_name)
    tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.model_name,
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
        device_map=None,
    ).to(device)

    # Load SFT data
    print(f"Loading {args.num_examples} SFT examples from {args.sft_dataset}...")
    train_data = load_sft_data(args.sft_dataset, args.num_examples, args.seed)
    print(f"Loaded {len(train_data)} training examples")

    # Load test data
    print("Loading GSM8K test set...")
    test_data = load_gsm8k_test(args.num_test, args.seed)

    # Evaluate before training
    print("Evaluating base model (before SFT)...")
    pre_accuracy = evaluate_model(model, tokenizer, test_data, device)
    print(f"Pre-SFT accuracy: {pre_accuracy:.2f}%")

    # Build HuggingFace dataset
    hf_dataset = build_hf_dataset(train_data, tokenizer, args.max_length)

    # Training arguments
    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.num_epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=4,
        learning_rate=args.learning_rate,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
        report_to="none",
        seed=args.seed,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=hf_dataset,
        data_collator=SFTDataCollator(tokenizer.pad_token_id),
    )

    # Train
    print(f"Training SFT model on {len(train_data)} examples for {args.num_epochs} epochs...")
    trainer.train()

    # Evaluate after training
    print("Evaluating SFT model (after training)...")
    post_accuracy = evaluate_model(model, tokenizer, test_data, device)
    print(f"Post-SFT accuracy: {post_accuracy:.2f}%")

    # Save results
    results = {
        "model_name": args.model_name,
        "num_examples": args.num_examples,
        "num_epochs": args.num_epochs,
        "pre_accuracy": pre_accuracy,
        "post_accuracy": post_accuracy,
    }
    with open(os.path.join(args.output_dir, "results.json"), "w") as f:
        json.dump(results, f, indent=2)

    print(f"\nResults saved to {args.output_dir}/results.json")
    print(f"Pre-SFT:  {pre_accuracy:.2f}%")
    print(f"Post-SFT: {post_accuracy:.2f}%")
    print(f"Improvement: +{post_accuracy - pre_accuracy:.2f}%")


if __name__ == "__main__":
    main()
